export const tools = [1, 2, 3, 4, 5, 6]

export const inviteTypes = {
	EDITOR: 'EDITOR',
	CONTRIBUTOR: 'CONTRIBUTOR'
}

export const ActionTypes = {
	SET_ACTIVE: 'SET_ACTIVE',
	UPDATE_ACTIVE: 'UPDATE_ACTIVE',
	SET_TOOL: 'SET_TOOL',
	SET_SENTENCES: 'SET_SENTENCES',
	NEXT_SENTENCE: 'Sup',
	PREV_SENTENCE: 'Sdown',
	DELETE_SENTENCE: 'DELETE_SENTENCE',
	ADD_SENTENCE: 'ADD_SENTENCE',
	MERGE_SENTENCE: 'MERGE_SENTENCE',
	UPDATE_SENTENCE: 'UPDATE_SENTENCE',
	NEXT_WORD: 'Wup',
	PREV_WORD: 'Wdown',
	DELETE_WORD: 'DELETE_Word',
	ADD_WORD: 'ADD_Word',
	MERGE_WORD: 'MERGE_Word',
	BREAK_SENTENCE: 'BREAK_SENTENCE',
	SIGN_IN: 'SIGN_IN',
	SIGN_OUT: 'SIGN_OUT',
	SET_NOTIFICATIONS:'SET_NOTIFICATIONS',
	ADD_NOTIFICATION:'ADD_NOTIFICATION',
	START_LOADING: 'START_LOADING',
	COMPLETE_LOADING: 'COMPLETE_LOADING'
}